version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: brews
    networks:
      - brew-net

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - brew-net
#
#  api:
#    build: .
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://devuser:devpassword@db/brews
#    ports:
#      - 5000:5000
#    restart: always

networks:
  brew-net:
    driver: bridge