version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: brews

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  api:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://devuser:devpassword@db/brews
    ports:
      - 5000:5000
    restart: always