version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: brews
    networks:
      - brew-net
    volumes:
      - /volume1/docker/postgres-data:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 18080:8080
    networks:
      - brew-net

  api:
    image: emilmadsen/thebeerhub-api:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devuser:devpassword@192.168.0.52:15432/brews  # todo
    ports:
      - 15000:5000
    restart: always
    networks:
      - brew-net

  ui:
    image: emilmadsen/thebeerhub-ui:latest
    depends_on:
      - api
    ports:
      - 10080:80
    restart: always
    networks:
      - brew-net

networks:
  brew-net:
    driver: bridge