"""add brew

Revision ID: dbd39cdead64
Revises: ff6c56c3cbfe
Create Date: 2021-03-07 01:33:39.523374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd39cdead64'
down_revision = 'ff6c56c3cbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brew',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brew_name', sa.String(length=255), nullable=False),
    sa.Column('brew_type', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('brewsters', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('recipe', sa.String(length=255), nullable=True),
    sa.Column('target_start_gravity', sa.Integer(), nullable=True),
    sa.Column('actual_start_gravity', sa.Integer(), nullable=True),
    sa.Column('target_end_gravity', sa.Integer(), nullable=True),
    sa.Column('actual_end_gravity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brew')
    # ### end Alembic commands ###
